class Comment < ActiveRecord::Base
  belongs_to :answer
  #belongs_to :answer was autogenerated by Rails 
  #via command line model creation command ~> rails g model comment body:text answer:references

end
